name = "OUILookup"
uuid = "40d79861-9d8c-4902-b083-62b07ea197bc"
authors = ["Anand Bisen"]
version = "0.1.0-DEV"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[compat]
Downloads = "1.6.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
